---
#Setup epel for downloading fail2ban
- name: Download epel RPM
  get_url: url="{{ epel_download_url }}" dest="{{epel_download_path}}" timeout=5
  environment: proxy_env

- name: Install epel RPM
  yum: name="{{epel_download_path}}" state=present
  environment: proxy_env



#Install fail2ban and enable it on startup
- name: Install fail2ban
  yum: name=fail2ban state=present

- name: Start and enable fail2ban service
  service: name=fail2ban state=started enabled=yes



#Configure history
- name: Configure history for all users with date/time and 100,000 lines of history
  copy: src=history.sh dest=/etc/profile.d/history.sh mode=755 owner=root group=root


#Restart iptables
- name: Restart iptables service 
#checking whether iptables is running is pointless
#restart would fail if there is no /etc/sysconfig/iptables file
  service: name=iptables state=restarted
  ignore_errors: yes


#Setup /etc/hosts
- name: Configure hostname and fqdn to resolve to local IP on first line of /etc/hosts
#Necessary for containers so that they can send emails without 30 second delay
  lineinfile: dest=/etc/hosts regexp="{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}" insertbefore="BOF" line="{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}"


#Logwatch configuration
- name: Install logwatch
  yum: name=logwatch state=installed
  environment: proxy_env

- name: Configure detailed logging via logwatch
  lineinfile: line="Detail = High" dest=/etc/logwatch/conf/logwatch.conf regexp="^Detail ="  


#SMTP configuration
- name: Install sendmail SMTP server for outgoing email
  yum: name=sendmail state=installed
  environment: proxy_env

- name: Ensure that postfix is stopped and disabled
  service: name=postfix enabled=no state=stopped
#if postfix is not present ignore error
  ignore_errors: yes

- name: Configure SMART_HOST if necessary
  lineinfile: line="define(`SMART_HOST', `{{smtp_smart_host}}')dnl" regexp="SMART_HOST" dest="/etc/mail/sendmail.mc"
  when: smtp_smart_host != "none"
  notify:
    - restart sendmail

- name: Ensure that sendmail is running and enabled
  service: name=sendmail enabled=yes state=started


#Configure private DNS if values are set 
- name: Configure machine to use private DNS (peerDNS)
  template: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=644
  when: private_dns_ips != "none" 
