---
# epel setup is taken care of by common role, so not required here again
#
#- name: Download epel RPM
#  get_url: url="{{ epel_download_url }}" dest="{{epel_download_path}}" timeout=5
#  environment: proxy_env
#
#- name: Install epel RPM
#  yum: name="{{epel_download_path}}" state=present
#  environment: proxy_env

- name: Install httpd, awstats, mod_ssl
  yum: name="{{item}}" state=present
  environment: proxy_env
  with_items:
    - httpd
    - awstats
    - mod_ssl

- name: Configure apache to support multiple virtualhosts
  lineinfile: line="NameVirtualHost *:80" regexp="^NameVirtualHost .*:80" dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart httpd

- name: Configure virtual-host for all proxy_domains
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/virtualhost.conf
  notify:
    - restart httpd

#Note that extra awstats file which are not deleted when a domain is removed from proxy_domains list 
#is not an issue
- name: Create one awstats file for each proxy domain
  template: src=awstats.reverseproxy.conf dest="/etc/awstats/awstats.{{item}}.conf"
  with_items: proxy_domains

- name: Allow access to awstats from everywhere
  copy: src=httpd_awstats.conf dest=/etc/httpd/conf.d/awstats.conf owner=root group=root mode=644
  notify:
    - restart httpd


#Configure firewall
- name: Configure iptables firewall
  template: src=reverseproxy_iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600
  notify: 
    - restart iptables
